# Generated by Django 5.2.3 on 2025-06-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='stock',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
