# Generated by Django 5.2.3 on 2025-06-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_menuitem_stock_menuitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], default='lunch', max_length=20),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
