# Generated by Django 5.2.3 on 2025-06-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuitem_category_menuitem_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='stock',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('juices', 'Juices'), ('snacks', 'Snacks'), ('beverages', 'Beverages')], default='snacks', max_length=20),
        ),
    ]
