# Generated by Django 5.2.3 on 2025-06-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanteenTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.TimeField(default='09:00')),
                ('closing_time', models.TimeField(default='17:00')),
            ],
        ),
    ]
